std_msgs/Header header
adu_common_control_controlcommand_msgs/control_header control_header
float64 throttle#: 2.807692100
float64 brake#: 0.000000000
float64 steering_rate#: 72.000000000
float64 steering_target#: -0.418964290
int32 high_beam#: 0
int32 low_beam#: 0
int32 left_turn#: 0
int32 right_turn#: 0
int32 driving_mode#: COMPLETE_AUTO_DRIVE
int32 gear_location#: GEAR_DRIVE
adu_common_control_controlcommand_msgs/contrl_context contrl_context