std_msgs/Header header
int32 VehicleSpeedValid#: 0
float64 VehicleSpeed#: 0.000000
int32 WheelSpeed_FL_Valid#: 1
float64 WheelSpeed_FL#: 0.000000
int32 WheelSpeed_FR_Valid#: 1
float64 WheelSpeed_FR#: 0.000000
float64 WheelSpeed_Front#: 0.000000
int32 WheelSpeed_RL_Valid#: 1
float64 WheelSpeed_RL#: 0.000000
int32 WheelSpeed_RR_Valid#: 1
float64 WheelSpeed_RR#: 0.000000
float64 WheelSpeed_Rear#: 15.000000
int32 Wheel_FL_Status#: 2
int32 Wheel_FR_Status#: 2
int32 Wheel_RL_Status#: 2
int32 Wheel_RR_Status#: 2
int32 VehicleRealDirect#: 2
