std_msgs/Header header
int32 engine_started#:1
float64 engine_rpm#:0.000000
float64 speed_mps#:0.000000
float64 odometer_m#:0.007188
float64 throttle_percentage#:0.000000
float64 brake_percentage#:0.000000
float64 steering_percentage#:-0.000000
int32 parking_brake#:1
int32 disengage_status#:0
int32 driving_mode#:COMPLETE_AUTO_DRIVE
int32 error_code#:NO_ERROR
int32 gear_location#:GEAR_PARKING
string vin#:LHT5C2A47LC6AA003
float64 extend_info_kinglong_dump_energy#:51.000000
int32   extend_info_kinglong_charge_state#: 1
int32 safety_msg_vehicle_whole_fault_level#: 5
int32 safety_msg_drive_system_fault_level#: 0